version: '3'
services:
  summarize:
    build: .
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./data:/data
    command: python topictrack/summarize.py /data/text.txt $TITLE
    tty: true